cars=['bwm','xiaomi','beyond','audi','will']

print("is "+cars[0]+"== 'bwm'?i predict True")
print(cars[0]=='bwm')
print("\nis "+cars[1]+"== 'xiaomi'?i predict True")
print(cars[1]=='xiaomi')
print("\nis "+cars[0]+"== 'xiaomi'?i predict False")
print(cars[0]=='xiaomi')
print("\nis "+cars[2]+"== 'beyond'?i predict True")
print(cars[2]=='bwm')
print("\nis "+cars[4]+"== 'will'?i predict True")
print(cars[4]=='will')
print("\nis "+cars[3]+"== 'audi'?i predict True")
print(cars[3]=='audi')

foods=['noodles','soup','rice','pizza','bread']
print("\nis "+foods[3]+"== 'noodles'?i predict False")
print(foods[3]=='noodles')
print("\nis "+foods[2]+"== 'bread'?i predict False")
print(foods[2]=='bread')
print("\nis "+foods[4]+"== 'pizza'?i predict False")
print(foods[4]=='bread')
print("\nis "+foods[1]+"== 'rice'?i predict False")
print(foods[1]=='rice')
print("\nis "+foods[0]+"== 'soup'?i predict False")
print(foods[0]=='soup')
