list=['mountain','country','tide','language','river']
list.append('happiness')
print("add happiness:")
print(list)
poped_list=list.pop(1)
print("\npop list[1]:")
print(list)
del list[1]
print("\ndelete list[1]")
print(list)
print("\nunchaged:")
print(sorted(list))
print(list)
print("\nunchaged:(1.0)")
print(sorted(list,reverse=True))
print(list)
list.reverse()
print("\nlist turn down")
print(list)
list.sort()
print("\nlist sort")
print(list)
list.sort(reverse=True)
print("\nlist sort in other way")
print(list)
