travel_places=['river','mountain huang','congqing','lake','sea']
print(travel_places)
print(sorted(travel_places))
print(travel_places)
print(sorted(travel_places,reverse=True))
print(travel_places)
travel_places.reverse()
print(travel_places)
travel_places.reverse()
print(travel_places)
travel_places.sort()
print(travel_places)
travel_places.sort(reverse=True)
print(travel_places)